"""Initial migration

Revision ID: 0c19701b15de
Revises: 
Create Date: 2024-12-23 15:59:48.517116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c19701b15de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('families',
    sa.Column('family_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('family_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('family_name')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driving_type', sa.Integer(), nullable=False),
    sa.Column('evaluation_status', sa.Integer(), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('acceralation_comment', sa.Text(), nullable=True),
    sa.Column('braking_comment', sa.Text(), nullable=True),
    sa.Column('cornering_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('sensors',
    sa.Column('sensor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('milage', sa.Integer(), nullable=False),
    sa.Column('average_speed', sa.Integer(), nullable=False),
    sa.Column('journey_time', sa.Integer(), nullable=False),
    sa.Column('longest_continuous_drive', sa.Integer(), nullable=False),
    sa.Column('idling_time', sa.Integer(), nullable=False),
    sa.Column('max_speed', sa.Integer(), nullable=False),
    sa.Column('acceralation_count', sa.Integer(), nullable=False),
    sa.Column('braking_count', sa.Integer(), nullable=False),
    sa.Column('cornering_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_table('reports')
    op.drop_table('families')
    op.drop_table('users')
    # ### end Alembic commands ###
